### PR TITLE
Add an integration with Coveralls

### PR DESCRIPTION
**Pull request by Jamim**
Here you can find how it looks like for my fork:
https://coveralls.io/github/Jamim/acf

### CODE REVIEW

**Comment by Jamim** [comment]
Hello @barjo,
Please approve my access request for Coveralls as well.
Thanks!

**Comment by Jamim** [comment]
And here is an alternative Codecov option:
https://codecov.io/gh/Jamim/acf/commits

**Comment by yuri-sagalovich** [comment]
> And here is an alternative Codecov option:
> https://codecov.io/gh/Jamim/acf/commits

I'd prefer the Codecov service, its interface looks more informative for me.

**Comment by Jamim** [comment]
Closed in favor of #3.

**Pull request closed without merging**
